"""FullTestPlan §2.1 — golden-content comparison.

Converts each real vendor file and compares the result field by field against
a committed JSON reference (tests/golden/, regenerated by make_golden.py).
Where test_sanity.py asks "did something plausible come out", these ask "did
*exactly* the known-correct values come out".

One data element per test function, parametrized across vendors, so a failure
names what broke and where: `test_units[sample_0.jpk]` rather than one
monolithic assertion that stops at the first mismatched field.

The references were captured from a trusted conversion, and for Bruker are
independently corroborated by the file's own ASCII header — see
test_vendor_header.py, which is what keeps this suite from merely asserting
that the converter still agrees with itself.
"""
from functools import lru_cache

import pytest

import gwyddionpy
from helpers import content as content_mod
from helpers.requirements import require_golden
from helpers.samples import IMAGE_SAMPLES, SAMPLES

pytestmark = [pytest.mark.converter, pytest.mark.formats]

IDS = lambda sample: sample.id  # noqa: E731 — parametrize id callback


@lru_cache(maxsize=None)
def _load(filename):
    """Convert once per session and reuse across the sub-tests.

    Conversion is the slow part and every sub-test needs the same result;
    the tests only read it. Keyed by filename because Sample is frozen and
    hashable but lru_cache keys read better as strings in tracebacks.
    """
    from helpers.samples import SAMPLES_BY_NAME

    return gwyddionpy.load(SAMPLES_BY_NAME[filename].path)


def _pair(sample):
    """(golden, freshly converted data) for a sample, or skip if unavailable."""
    require_golden(sample)
    return content_mod.load_golden(sample), _load(sample.filename)


def _channels(golden, data):
    """Yield (name, golden_channel, actual_channel) for channels in both.

    Names present in only one side are deliberately not reported here:
    test_channel_names owns that comparison, so a renamed channel produces
    one clear failure instead of the same news repeated by every sub-test.
    """
    for name, expected in golden["channels"].items():
        if name in data.channels:
            yield name, expected, data.channels[name]


# --------------------------------------------------------------------------
# File-level elements
# --------------------------------------------------------------------------
@pytest.mark.parametrize("sample", SAMPLES, ids=IDS)
def test_source_format(sample):
    """The Gwyddion module that claimed the file — i.e. format detection."""
    golden, data = _pair(sample)
    assert data.source_format == golden["source_format"]


@pytest.mark.parametrize("sample", SAMPLES, ids=IDS)
def test_channel_names(sample):
    """Channel names *and their order* (file order, which callers index by)."""
    golden, data = _pair(sample)
    assert list(data.channels) == golden["channel_names"]


# --------------------------------------------------------------------------
# Per-channel data elements
# --------------------------------------------------------------------------
@pytest.mark.parametrize("sample", IMAGE_SAMPLES, ids=IDS)
def test_channel_shapes(sample):
    golden, data = _pair(sample)
    diffs = [
        f"{name}: expected shape {tuple(expected['shape'])}, "
        f"got {actual.data.shape}"
        for name, expected, actual in _channels(golden, data)
        if list(actual.data.shape) != expected["shape"]
    ]
    assert not diffs, "channel shapes changed:\n" + content_mod.format_diffs(diffs)


@pytest.mark.parametrize("sample", IMAGE_SAMPLES, ids=IDS)
def test_scan_dimensions(sample):
    """Physical scan size (xreal/yreal) — wrong here means every derived
    length, area and lateral calibration downstream is wrong too."""
    golden, data = _pair(sample)
    diffs = []
    for name, expected, actual in _channels(golden, data):
        diffs += content_mod.float_diffs(
            {"xreal": expected["xreal"], "yreal": expected["yreal"]},
            {"xreal": actual.xreal, "yreal": actual.yreal},
            where=f"{name}.",
        )
    assert not diffs, "scan dimensions changed:\n" + content_mod.format_diffs(diffs)


@pytest.mark.parametrize("sample", IMAGE_SAMPLES, ids=IDS)
def test_units(sample):
    golden, data = _pair(sample)
    diffs = []
    for name, expected, actual in _channels(golden, data):
        for field, got in (("si_unit_xy", actual.si_unit_xy),
                           ("si_unit_z", actual.si_unit_z)):
            if got != expected[field]:
                diffs.append(f"{name}.{field}: expected {expected[field]!r}, "
                             f"got {got!r}")
    assert not diffs, "units changed:\n" + content_mod.format_diffs(diffs)


@pytest.mark.parametrize("sample", IMAGE_SAMPLES, ids=IDS)
def test_pixel_values(sample):
    """Spot pixels at fixed positions (corners, centre, interior fractions).

    This is the assertion the previous suite lacked entirely: it checked that
    values were finite, never that they were *right*.
    """
    golden, data = _pair(sample)
    diffs = []
    for name, expected, actual in _channels(golden, data):
        got = {
            key: actual.data[int(row), int(col)]
            for key in expected["samples"]
            for row, col in [key.split(",")]
        }
        diffs += content_mod.float_diffs(expected["samples"], got, where=f"{name} @ ")
    assert not diffs, "pixel values changed:\n" + content_mod.format_diffs(diffs)


@pytest.mark.parametrize("sample", IMAGE_SAMPLES, ids=IDS)
def test_statistics(sample):
    """min/max/mean/std over the whole array — catches a scaling or offset
    change that happens to leave the sampled pixels untouched."""
    golden, data = _pair(sample)
    diffs = []
    for name, expected, actual in _channels(golden, data):
        actual_stats = content_mod.channel_content(actual)["stats"]
        diffs += content_mod.float_diffs(
            expected["stats"], actual_stats, where=f"{name}.stats."
        )
    assert not diffs, "channel statistics changed:\n" + content_mod.format_diffs(diffs)


@pytest.mark.parametrize("sample", IMAGE_SAMPLES, ids=IDS)
def test_metadata(sample):
    """Vendor metadata, compared exactly.

    Kept as its own sub-test on purpose: metadata is the element most likely
    to drift legitimately between Gwyddion versions (a release adding a header
    key). If the 2.60 and 2.71 CI legs ever disagree, only this test needs a
    per-version policy — the numeric elements above stay strict.
    """
    golden, data = _pair(sample)
    diffs = []
    for name, expected, actual in _channels(golden, data):
        diffs += [f"{name}.{d}" for d in content_mod.meta_diffs(
            expected["meta"], actual.meta)]
    assert not diffs, "vendor metadata changed:\n" + content_mod.format_diffs(diffs)
